### ISSUE TITLE
mdt + bxx files need to be merged for hexagon elf?

### ISSUE THREAD

**Issue by lucasduffey** [programa-stic/hexag00n#3]
trying to figure out how to use your tools

For android: my assumption is the mdt + bxx files need to be merged into a single file which would be the hexagon elf - is this incorrect? Are you assuming the user does the before running your toolset?

**Comment by schomatis** [comment]
Hi Lucas, the short answer is Yes.

Those files you mention are loaded (merged) by the [peripheral image loader](https://github.com/gokulnatha/GT-I9505/blob/master/Documentation/devicetree/bindings/pil/pil-mba.txt) (PIL) into a single contiguous executable program.

IDA processor modules (like the one provide in this repository for Hexagon) rely on IDA loader modules to load and interpret the input file (in a similar way as an operating system loader would), e.g., mapping a string of bytes from the binary that encode an instruction into memory, so the processor module can later disassemble them into an instruction.

There is no (to my knowledge) IDA loader module available that can handle those files as the PIL would (which would be desirable), so those files (that represent an ELF executable, as you can see by checking the `'ELF'` magic number) have to be merged by you (there are tools available on the web that can do this) before using IDA to analyze them (this is not a limitation of the IDA processor module itself, rather the limitation is not having the IDA loader module).

You can also analyze each separate file, indicating IDA to load it as a "Binary file" (i.e., plain binary with no additional information) which is not the most convenient way, but may be enough for your needs.

**Comment by lucasduffey** [comment]
for the purpose of anyone else reading this

this might do it: https://github.com/laginimaineb/unify_trustlet

**Comment by schomatis** [comment]
Great, thanks for the link.
